---
title: "Analysis Report RIDER 3 - Reporting data both numerically and graphically"
pdf_document:
  toc: yes
  number_sections: yes
date: "2022-05-15"
output:
  html_document:
    toc: yes
    toc_depth: '3'
    df_print: paged
  word_document:
    toc: yes
    toc_depth: '3'
  pdf_document:
    toc: yes
    toc_depth: 3
    number_sections: yes
fig_height: 2
fig_width: 4
---

```{r setup, include=FALSE,fig.dim = c(4, 2)}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
rm(list = ls()) #clean environment
#Libraries
library(plyr) #Ssplitting, applying and combining Data
library(dplyr) # for general data manipulation
library(ggplot2) # for visualizations
library(purrr)#working with functions and vectors
library(stringr)#working with strings
library(purrr)# for plotting
library(tidyverse)#different aspects of data processing
library(reshape)# for general data manipulation
library(scico)#colour palettes fpr plotting
library("readxl")
library(circular)
library(Rmisc)
library(ggpubr)# for plotting
library(rstatix)#for stats
library(viridis)# for nice plotting colors
library(data.table)
#library(smplot)#for stats plots
library(BayesFactor)#for performing a Bayesian t-test
library(cowplot)#for plotting
library(ggstatsplot)
library(formatR)
library(PupillometryR)
`%notin%` <- Negate(`%in%`)

```



```{r loading data, include=FALSE}
# RIDER3 data
data_WM <- read.csv("/Users/born/Documents/RIDER3/client/public/data/WM_data_RIDER_3.csv",na.strings=c("","NA"))

data_LTM <- read.csv("/Users/born/Documents/RIDER3/client/public/data/LTM_data_RIDER_3.csv",na.strings=c("","NA"))

# removing timeout trials from LTM
data_LTM <- data_LTM[!(as.character(data_LTM$timeout_ltm) == "1"), ]
```


```{r calculating accurcy RIDER3, include=FALSE}

# Group the data by participant and remove the first 6 trials for each participant
data_WM <- data_WM %>%
  group_by(participant) %>%
  slice(7:n()) %>%
  ungroup()

# Identify the row indices that have been deleted
practice_trials <- data_WM %>%
  group_by(participant) %>%
  slice(1:6)


#calculating the correct fixed orientations for the 2-item trials:
#depending on whether the stimulus was presented in image 1 or image 2

data_WM$startOri1 <- as.character(data_WM$startOri1)

# here I determine the orientation the test image was presented in and give it the name fixedOri_t1
data_WM <- data_WM %>%
  rowwise() %>%
  mutate(
    fixedOri_t1 = case_when(
      test1 == image1 ~ as.numeric(startOri1),
      test1 == image2 ~ as.numeric(startOri2),
      TRUE ~ NA_real_
    )
  )
# calculate remainder of this_ori variable to adjust for cases that are beyond 360 degrees
data_WM <- data_WM %>% mutate(ori_t1_corrected = this_ori_t1 %% 360)#Modulus (Remainder from division)


data_WM$fixedOri_t1 <- as.numeric(data_WM$fixedOri_t1)


# calculating accuracy for test 1 and test 2
# function

angdiff <- function(alpha_deg, beta_deg) {
  #The function assumes that the input angles alpha and beta are in radians.So, you will have to convert them to radians first:
  alpha_rad <- alpha_deg * pi / 180
  beta_rad <- beta_deg * pi / 180
  # Then, you calculate the difference in angles
  delta_rad <- alpha_rad - beta_rad
  # If your input angles alpha and beta are larger than 360째, the mod() function will correctly wrap them to the range of [-180,180] degrees interval.
  delta_rad <- (delta_rad + pi) %% (2*pi) - pi
  delta_deg <- delta_rad * 180 / pi
  #the function outputs both the angular difference in degrees and in radians
  return(list(delta_rad = delta_rad, delta_deg = delta_deg))
}

# accuracy in radians
data_WM$accuracy_t1_rad <- apply(data_WM[,c("this_ori_t1", "fixedOri_t1")], 1, function(x) angdiff(x[1], x[2])$delta_rad)

# accuracy in degrees
data_WM$accuracy_t1 <- abs(apply(data_WM[,c("this_ori_t1", "fixedOri_t1")], 1, function(x) angdiff(x[1], x[2])$delta_deg))


# calculate ltm accuracy
data_LTM <- data_LTM %>% mutate(ori_ltm = this_ori_ltm %% 360)#Modulus (Remainder from division)


# calculating accuracy for LTM test

data_LTM <- data_LTM %>% 
  rowwise() %>%
  mutate(min_angle_ltm = abs(ori_ltm -fixedOri_ltm))%>%
  mutate(max_angle_ltm = 360-abs(ori_ltm -fixedOri_ltm))

data_LTM <- transform(data_LTM, accuracy_ltm = pmin(min_angle_ltm, max_angle_ltm))#angular difference



data_LTM$accuracy_ltm_rad <- (apply(data_LTM[,c("this_ori_ltm", "fixedOri_ltm")], 1, function(x) angdiff(x[1], x[2])$delta_rad))


```


```{r renaming trial types, echo=FALSE}
data_WM <- data_WM  %>% 
  mutate(trial_type_new = case_when(
    trial_type == "attended_1" ~ "attended",
    trial_type == "attended_2" ~ "attended",
    trial_type == "attended_3" ~ "attended",
    trial_type == "attended_4" ~ "attended",
    trial_type == "attended_5" ~ "attended",
    trial_type == "unattended" ~ "unattended"))


data_WM <- data_WM  %>% 
  mutate(image_effect = case_when(
    trial_type == "attended_1" & image1 %in%  test1 ~ "Image1-attended",
    trial_type == "attended_1" & image2 %in%  test1 ~ "Image2-attended",
    trial_type == "attended_2" & image1 %in%  test1 ~ "Image1-attended",
    trial_type == "attended_2" & image2 %in%  test1 ~ "Image2-attended",
    trial_type == "attended_3" & image1 %in%  test1 ~ "Image1-attended",
    trial_type == "attended_3" & image2 %in%  test1 ~ "Image2-attended",
    trial_type == "attended_4" & image1 %in%  test1 ~ "Image1-attended",
    trial_type == "attended_4" & image2 %in%  test1 ~ "Image2-attended",
    trial_type == "attended_5" & image1 %in%  test1 ~ "Image1-attended",
    trial_type == "attended_5" & image2 %in%  test1 ~ "Image2-attended",
    trial_type == "unattended" & image1 %in%  test1 ~ "Image1-unattended",
    trial_type == "unattended" & image2 %in%  test1 ~ "Image2-unattended",))

data_LTM <- rbind.fill(data_LTM,data_WM[c("test1","participant","image1","image2")])

data_LTM <- data_LTM %>%
  group_by(participant)%>%
  mutate(trial_type = case_when(ltm_trial == 'attended_1' & ltm_image %in%  test1 ~ "attended",
                                 ltm_trial == 'attended_2' & ltm_image %in%  test1 ~ "attended",
                                 ltm_trial == 'attended_3' & ltm_image %in%  test1 ~ "attended",
                                 ltm_trial == 'attended_4' & ltm_image %in%  test1 ~ "attended",
                                 ltm_trial == 'attended_5' & ltm_image %in%  test1 ~ "attended",
                                 ltm_trial == 'unattended' & ltm_image %in%  test1 ~ "unattended",
                                 ltm_trial == 'unattended' & ltm_image %notin% test1  ~ "attended-never tested",
                                 ltm_trial == 'attended_1' & ltm_image %notin% test1  ~ "unattended-never tested",
                                 ltm_trial == 'attended_2' & ltm_image %notin% test1  ~ "unattended-never tested",
                                 ltm_trial == 'attended_3' & ltm_image %notin% test1  ~ "unattended-never tested",
                                 ltm_trial == 'attended_4' & ltm_image %notin% test1  ~ "unattended-never tested",
                                 ltm_trial == 'attended_5' & ltm_image %notin% test1  ~ "unattended-never tested"))


# data_LTM <- data_LTM %>%
#   group_by(participant)%>%
#   mutate(trial_type = case_when(ltm_trial == 'attended_1' & ltm_image %in%  test1 ~ "attended",
#                                  ltm_trial == 'attended_2' & ltm_image %in%  test1 ~ "attended",
#                                  ltm_trial == 'attended_3' & ltm_image %in%  test1 ~ "attended",
#                                  ltm_trial == 'unattended' & ltm_image %in%  test1 ~ "unattended",
#                                  ltm_trial == 'unattended' & ltm_image %notin% test1  ~ "never tested",
#                                  ltm_trial == 'attended_1' & ltm_image %notin% test1  ~ "never tested",
#                                  ltm_trial == 'attended_2' & ltm_image %notin% test1  ~ "never tested",
#                                  ltm_trial == 'attended_3' & ltm_image %notin% test1  ~ "never tested"))

data_LTM <- data_LTM %>%
  group_by(participant)%>%
  mutate(image_effect = case_when(ltm_trial == 'attended_1' & ltm_image %in%  test1 & ltm_image %in%  image1 ~ "Image1-attended",
                                  ltm_trial == 'attended_2' & ltm_image %in%  test1 & ltm_image %in%  image1 ~ "Image1-attended",
                                  ltm_trial == 'attended_3' & ltm_image %in%  test1 & ltm_image %in%  image1 ~ "Image1-attended",
                                  ltm_trial == 'attended_1' & ltm_image %in%  test1 & ltm_image %in%  image2 ~ "Image2-attended",
                                  ltm_trial == 'attended_2' & ltm_image %in%  test1 & ltm_image %in%  image2 ~ "Image2-attended",
                                  ltm_trial == 'attended_3' & ltm_image %in%  test1 & ltm_image %in%  image2 ~ "Image2-attended",
                                  ltm_trial == 'attended_4' & ltm_image %in%  test1 & ltm_image %in%  image2 ~ "Image2-attended",
                                  ltm_trial == 'attended_5' & ltm_image %in%  test1 & ltm_image %in%  image2 ~ "Image2-attended",
                                  ltm_trial == 'attended_4' & ltm_image %in%  test1 & ltm_image %in%  image1 ~ "Image1-attended",
                                  ltm_trial == 'attended_5' & ltm_image %in%  test1 & ltm_image %in%  image1 ~ "Image1-attended",
                                  ltm_trial == 'unattended' & ltm_image %in%  test1 & ltm_image %in%  image1 ~ "Image1-unattended",
                                  ltm_trial == 'unattended' & ltm_image %in%  test1 & ltm_image %in%  image2 ~ "Image2-unattended",
                                  ltm_trial == 'unattended' & ltm_image %notin% test1 & ltm_image %in%  image2 ~ "Image2-attended-never tested",
                                  ltm_trial == 'unattended' & ltm_image %notin% test1 & ltm_image %in%  image1 ~ "Image1-attended-never tested",
                                  ltm_trial == 'attended_1' & ltm_image %notin% test1 & ltm_image %in%  image2 ~ "Image2-unattended-never tested",
                                  ltm_trial == 'attended_1' & ltm_image %notin% test1 & ltm_image %in%  image1 ~ "Image1-unattended-never tested",
                                  ltm_trial == 'attended_2' & ltm_image %notin% test1 & ltm_image %in%  image2 ~ "Image2-unattended-never tested",
                                  ltm_trial == 'attended_2' & ltm_image %notin% test1 & ltm_image %in%  image1 ~ "Image1-unattended-never tested",
                                  ltm_trial == 'attended_3' & ltm_image %notin% test1 & ltm_image %in%  image2 ~ "Image2-unattended-never tested",
                                  ltm_trial == 'attended_3' & ltm_image %notin% test1 & ltm_image %in%  image1 ~ "Image1-unattended-never tested",
                                  ltm_trial == 'attended_4' & ltm_image %notin% test1 & ltm_image %in%  image2 ~ "Image2-unattended-never tested",
                                  ltm_trial == 'attended_4' & ltm_image %notin% test1 & ltm_image %in%  image1 ~ "Image1-unattended-never tested",
                                  ltm_trial == 'attended_5' & ltm_image %notin% test1 & ltm_image %in%  image2 ~ "Image2-unattended-never tested",
                                  ltm_trial == 'attended_5' & ltm_image %notin% test1 & ltm_image %in%  image1 ~ "Image1-unattended-never tested"))



#remove extra WM rows again
data_LTM <- data_LTM[rowSums(is.na(data_LTM)) == 0|rowSums(is.na(data_LTM)) == 1| rowSums(is.na(data_LTM)) == 2|rowSums(is.na(data_LTM)) == 3|rowSums(is.na(data_LTM)) == 4,]


# data_LTM <- data_LTM  %>% 
#   mutate(trial_type = case_when(
#     ltm_trial == "attended_1" ~ "attended",
#     ltm_trial == "attended_2" ~ "attended",
#     ltm_trial == "attended_3" ~ "attended",
#     ltm_trial == "unattended" ~ "unattended"))

```


```{r WM Outlier, include=TRUE}

# did not do the task 
data_WM<-data_WM[!(data_WM$participant==63),]
data_LTM<-data_LTM[!(data_LTM$participant==63),]

#data_WM<-data_WM[!(data_WM$participant==52),]
#data_LTM<-data_LTM[!(data_LTM$participant==52),]
data_WM<-data_WM[!(data_WM$participant==32),]
data_LTM<-data_LTM[!(data_LTM$participant==32),]
#data_WM<-data_WM[!(data_WM$participant==46),]
#data_LTM<-data_LTM[!(data_LTM$participant==46),]
#data_WM<-data_WM[!(data_WM$participant==12),]
#data_LTM<-data_LTM[!(data_LTM$participant==12),]

#data_WM<-data_WM[!(data_WM$participant==40),]
#data_LTM<-data_LTM[!(data_LTM$participant==40),]
#data_WM<-data_WM[!(data_WM$participant==46),]
#data_LTM<-data_LTM[!(data_LTM$participant==46),]
#data_WM<-data_WM[!(data_WM$participant==49),]
#data_LTM<-data_LTM[!(data_LTM$participant==49),]
#data_WM<-data_WM[!(data_WM$participant==56),]
#data_LTM<-data_LTM[!(data_LTM$participant==56),]
#data_WM<-data_WM[!(data_WM$participant==70),]
#data_LTM<-data_LTM[!(data_LTM$participant==70),]


cat("There are", length(unique(data_WM$participant)),"participants in our anaylsis. The following might be considered outliers")


data_outliers <- data_WM %>%
  select(accuracy_t1,trial_type_new,participant)%>%
  group_by(participant)%>%
  summarise(value = list(accuracy_t1))%>%
  group_by(participant)%>%
  mutate(p_value = t.test(unlist(value),mu = 90,alternative = c('less'))$p.value, 
        t_value = t.test(unlist(value),mu = 90,alternative = c('less'))$statistic,
        mean = t.test(unlist(value),mu = 90,alternative = c('less'))$estimate)

data_outliers %>% filter(p_value > 0.05)


```


```{r performance filter WM, include=TRUE}
# filtering for participants with WM performance below sealing

# mean_performance <- summarySE(data_WM, measurevar = "accuracy_t1", groupvars = c("participant","trial_type_new"),na.rm = T)
# 
# # create a logical vector for filtering
# filter_vec <- (data_WM$accuracy_t1 <= 10)
# 
# # filter the data
# data_LTM_best_participants <- data_LTM[filter_vec,]


```



```{r pruning, include=FALSE}


#data_WM <-data_WM %>% drop_na(log_response_t1.keys)

#check for timeout trials in the WM task 
timeout_WM <- data_WM %>% filter(is.na(adjust_keys_t1.rt))

data_WM <- data_WM %>% filter(!is.na(adjust_keys_t1.rt))

objects_time_out <- timeout_WM %>%
  group_by(participant,trial_type_new)%>%
  summarise(image1,image2)


objects_time_out<- objects_time_out %>% pivot_longer(cols=c('image1', 'image2'),names_to='Presentation',values_to='image1') 

# identification of ltm object pool that includes only pruned WM conditions (Test 1 and Test 2 is effected here)
data_LTM <- rbind.fill(data_LTM,objects_time_out[c("participant", "image1")])

data_LTM <- data_LTM %>%
  group_by(participant)%>%
  mutate(matching = case_when(ltm_image %in% image1  ~ "Match",
                              ltm_image %notin%  image1  ~   "NO_Match"))


data_LTM <- data_LTM[rowSums(is.na(data_LTM)) == 1|rowSums(is.na(data_LTM)) == 2|rowSums(is.na(data_LTM)) == 3|rowSums(is.na(data_LTM)) == 4,]

# delete all matching trials in ltm dataframe
data_LTM<-data_LTM[!(data_LTM$matching=="Match"),]



removed_trials <-data.frame(matrix(ncol=22,nrow=0, dimnames=list(NULL, colnames(data_WM))))
data_WM_after_pruning <- data_WM

######current approach
for (i in data_WM$participant){
  # select trials per participant
  attended_trials <- data_WM[which(data_WM$trial_type_new=='attended' & data_WM$participant == i), ]
  unattended_trials <- data_WM[which(data_WM$trial_type_new=='unattended' & data_WM$participant == i), ]
  # order mean values for each trial type to know what to prune
  vector <- c(mean(attended_trials$accuracy_t1,na.rm = TRUE),mean(unattended_trials$accuracy_t1,na.rm = TRUE))
  # find the reference for pruning (will be baseline for most participants)
  lowest <- mean(vector)
  # order the single values to prepare to remove them to equalize the means
  attended_trials <- attended_trials[order(attended_trials$accuracy_t1,decreasing = TRUE),]
  unattended_trials <- unattended_trials[order(unattended_trials$accuracy_t1,decreasing = TRUE),]
  while (mean(attended_trials$accuracy_t1,na.rm = TRUE) > lowest){
    removed <- attended_trials[1,]
    attended_trials <- attended_trials[-1,]
    removed_trials[nrow(removed_trials) + 1, ] <- removed
  }
  while (mean(unattended_trials$accuracy_t1,na.rm = TRUE) > lowest){
    removed <- unattended_trials[1,]
    unattended_trials <- unattended_trials[-1,]
    removed_trials[nrow(removed_trials) + 1, ] <- removed
  }
  print(i)
}

removed_trials <- removed_trials[!duplicated(removed_trials[,]),]

dataframe1 <- anti_join(data_WM, removed_trials)

final_accuracy_summary <- dataframe1 %>%
  group_by(participant, trial_type_new) %>%
  summarize(mean_accuracy = mean(accuracy_t1, na.rm = TRUE))

objects <- removed_trials %>%
  group_by(participant,trial_type_new)%>%
  summarise(image1, image2)

objects<- objects %>% pivot_longer(cols=c('image1', 'image2'),names_to='Presentation',values_to='test1') 

# identification of ltm object pool that includes only pruned WM conditions (Test 1 and Test 2 is effected here)

data_LTM <- rbind.fill(data_LTM,objects[c("participant", "test1")])

data_LTM <- data_LTM %>%
  group_by(participant)%>%
  mutate(matching = case_when(ltm_image %in% test1  ~ "Match",
                              ltm_image %notin%  test1  ~   "NO_Match"))


data_LTM <- data_LTM[rowSums(is.na(data_LTM)) == 1|rowSums(is.na(data_LTM)) == 2|rowSums(is.na(data_LTM)) == 3|rowSums(is.na(data_LTM)) == 4,]

# delete all matching trials in ltm dataframe
data_LTM_pruned<-data_LTM[!(data_LTM$matching=="Match"),]




```



## Working Memory accuracy trial type


```{r accuracy WM trial type, echo=FALSE}
summary_stats_participant_trial_type <- summarySE(data_WM, measurevar = "accuracy_t1", groupvars = c("trial_type_new","participant"),na.rm = T)
summary_study_level_trial_type <- summarySE(data_WM, measurevar = "accuracy_t1", groupvars = c("trial_type_new"),na.rm = T)

summary_stats_participant_trial_type <-summary_stats_participant_trial_type %>%
  rowwise()%>%
  mutate(accuracy = (90-accuracy_t1))

summary_study_level_trial_type <-summary_study_level_trial_type %>%
  rowwise()%>%
  mutate(accuracy = (90-accuracy_t1))


num_participants <- length(unique(data_WM$participant))

green_colors <- colorRampPalette(c("#00FF00", "forestgreen"))(num_participants)

ggplot(summary_stats_participant_trial_type, aes(x = factor(trial_type_new), y = accuracy, color = as.factor(participant))) +
  geom_line(aes(group = participant), alpha = 1.5/5) +
  geom_point(data = summary_study_level_trial_type, aes(x = trial_type_new, y = accuracy),  colour = "black", size = 2) +
  geom_errorbar(data = summary_study_level_trial_type, aes(x = trial_type_new, ymin = accuracy - se, ymax = accuracy + se), width = 0.15, colour = "black", size = 0.8) +
  geom_line(data = summary_study_level_trial_type, aes(x = trial_type_new, group = 1), colour = "black", size = 0.7) +
  stat_summary(fun.y = mean, colour = "blue", geom = "text", show_guide = FALSE, vjust = -2, aes(label = (round(..y.., digits = 1)*(1)))) +
  ylim(c(-20, 90)) + 
  ylab('Angular difference to chance level (in 째)\n\n') +
  xlab('\n\nExperimental condition') +
  guides(color = "none") +
  labs(title = 'WM (including all participants') +
  theme_minimal() +
  scale_color_manual(values = green_colors) +  # Set the orangy color palette
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.title = element_text(size = 13))



```



```{r pairwise t-test WM, echo=FALSE}
print("The following pairwise t-test tests the difference between attended and unattended storage in WM")

full_data_summary <-data_WM %>%
  group_by(trial_type_new, participant) %>%
  get_summary_stats(accuracy_t1, type = "mean_sd")


full_data_summary %>%
  pairwise_t_test(
    mean ~ trial_type_new, paired = TRUE,
    p.adjust.method = "holm")


```



```{r accuracy WM trial type after pruning, echo=FALSE}
summary_stats_participant_trial_type <- summarySE(dataframe1, measurevar = "accuracy_t1", groupvars = c("trial_type_new","participant"),na.rm = T)
summary_study_level_trial_type <- summarySE(dataframe1, measurevar = "accuracy_t1", groupvars = c("trial_type_new"),na.rm = T)

summary_stats_participant_trial_type <-summary_stats_participant_trial_type %>%
  rowwise()%>%
  mutate(accuracy = (90-accuracy_t1))

summary_study_level_trial_type <-summary_study_level_trial_type %>%
  rowwise()%>%
  mutate(accuracy = (90-accuracy_t1))


num_participants <- length(unique(data_WM$participant))

green_colors <- colorRampPalette(c("#00FF00", "forestgreen"))(num_participants)

ggplot(summary_stats_participant_trial_type, aes(x = factor(trial_type_new), y = accuracy, color = as.factor(participant))) +
  geom_line(aes(group = participant), alpha = 1.5/5) +
  geom_point(data = summary_study_level_trial_type, aes(x = trial_type_new, y = accuracy),  colour = "black", size = 2) +
  geom_errorbar(data = summary_study_level_trial_type, aes(x = trial_type_new, ymin = accuracy - se, ymax = accuracy + se), width = 0.15, colour = "black", size = 0.8) +
  geom_line(data = summary_study_level_trial_type, aes(x = trial_type_new, group = 1), colour = "black", size = 0.7) +
  stat_summary(fun.y = mean, colour = "blue", geom = "text", show_guide = FALSE, vjust = -2, aes(label = (round(..y.., digits = 1)*(1)))) +
  ylim(c(-20, 90)) + 
  ylab('Angular difference to chance level (in 째)\n\n') +
  xlab('\n\nExperimental condition') +
  guides(color = "none") +
  labs(title = 'WM after Pruning') +
  theme_minimal() +
  scale_color_manual(values = green_colors) +  # Set the orangy color palette
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.title = element_text(size = 13))



```
## Image effect in WM


```{r accuracy WM image effect, echo=FALSE}

summary_stats_participant_trial_type_ie <- summarySE(data_WM, measurevar = "accuracy_t1", groupvars = c("image_effect","participant"),na.rm = T)
summary_study_level_trial_type_ie <- summarySE(data_WM, measurevar = "accuracy_t1", groupvars = c("image_effect"),na.rm = T)

summary_stats_participant_trial_type_ie <-summary_stats_participant_trial_type_ie %>%
  rowwise()%>%
  mutate(accuracy = (90-accuracy_t1))

summary_study_level_trial_type_ie <-summary_study_level_trial_type_ie %>%
  rowwise()%>%
  mutate(accuracy = (90-accuracy_t1))

num_participants <- length(unique(data_WM$participant))

green_colors <- colorRampPalette(c("#00FF00", "forestgreen"))(num_participants)


level_order <- c('Image1-attended', 'Image2-attended', 'Image1-unattended','Image2-unattended')


ggplot(summary_stats_participant_trial_type_ie, aes(x = factor(image_effect,level = level_order), y = accuracy, color = as.factor(participant))) +
  geom_line(aes(group = participant), alpha = 1.5/5) +
  geom_point(data = summary_study_level_trial_type_ie, aes(x = image_effect, y = accuracy),  colour = "black", size = 2) +
  geom_errorbar(data = summary_study_level_trial_type_ie, aes(x = image_effect, ymin = accuracy - se, ymax = accuracy + se), width = 0.15, colour = "black", size = 0.8) +
  geom_line(data = summary_study_level_trial_type_ie, aes(x = image_effect, group = 1), colour = "black", size = 0.7) +
  stat_summary(fun.y = mean, colour = "blue", geom = "text", show_guide = FALSE, vjust = -2, aes(label = (round(..y.., digits = 1)*(1)))) +
  ylim(c(-20, 90)) + 
  ylab('Angular difference to chance level (in 째)\n\n') +
  xlab('\n\nExperimental condition') +
  guides(color = "none") +
  labs(title = 'WM recency effect?') +
  theme_minimal() +
  scale_color_manual(values = green_colors) +  # Set the orangy color palette
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(plot.title = element_text(size = 13))


```

```{r LTM Outlier, include=TRUE}


#data_WM<-data_WM[!(data_WM$participant==70),]
#data_LTM<-data_LTM[!(data_LTM$participant==70),]


cat("There are", length(unique(data_LTM$participant)),"participants in our anaylsis. The following might be considered outliers")


data_outliers <- data_LTM %>%
  select(accuracy_ltm,trial_type,participant)%>%
  group_by(participant)%>%
  summarise(value = list(accuracy_ltm))%>%
  group_by(participant)%>%
  mutate(p_value = t.test(unlist(value),mu = 90,alternative = c('less'))$p.value, 
        t_value = t.test(unlist(value),mu = 90,alternative = c('less'))$statistic,
        mean = t.test(unlist(value),mu = 90,alternative = c('less'))$estimate)

data_outliers %>% filter(p_value > 0.01)

data_LTM<-data_LTM[!(data_LTM$participant==12),]
data_LTM<-data_LTM[!(data_LTM$participant==20),]
data_LTM<-data_LTM[!(data_LTM$participant==21),]
data_LTM<-data_LTM[!(data_LTM$participant==26),]
data_LTM<-data_LTM[!(data_LTM$participant==55),]
data_LTM<-data_LTM[!(data_LTM$participant==56),]
data_LTM<-data_LTM[!(data_LTM$participant==73),]
data_LTM<-data_LTM[!(data_LTM$participant==83),]
data_LTM<-data_LTM[!(data_LTM$participant==48),]
data_LTM<-data_LTM[!(data_LTM$participant==54),]


data_LTM_pruned<-data_LTM_pruned[!(data_LTM_pruned$participant==12),]
data_LTM_pruned<-data_LTM_pruned[!(data_LTM_pruned$participant==20),]
data_LTM_pruned<-data_LTM_pruned[!(data_LTM_pruned$participant==21),]
data_LTM_pruned<-data_LTM_pruned[!(data_LTM_pruned$participant==26),]
data_LTM_pruned<-data_LTM_pruned[!(data_LTM_pruned$participant==55),]
data_LTM_pruned<-data_LTM_pruned[!(data_LTM_pruned$participant==56),]
data_LTM_pruned<-data_LTM_pruned[!(data_LTM_pruned$participant==73),]
data_LTM_pruned<-data_LTM_pruned[!(data_LTM_pruned$participant==83),]
data_LTM_pruned<-data_LTM_pruned[!(data_LTM_pruned$participant==48),]
data_LTM_pruned<-data_LTM_pruned[!(data_LTM_pruned$participant==54),]




```










## Long-term memory accuracy

```{r accuracy LTM trial type, echo=FALSE}

summary_stats_participant_LTM <- summarySE(data_LTM, measurevar = "accuracy_ltm", groupvars = c("trial_type","participant"),na.rm = T)
summary_study_level_LTM <- summarySE(data_LTM, measurevar = "accuracy_ltm", groupvars = c("trial_type"),na.rm = T)

num_participants <- length(unique(data_WM$participant))

summary_stats_participant_LTM <-summary_stats_participant_LTM %>%
  rowwise()%>%
  mutate(accuracy = (90 - accuracy_ltm))

summary_study_level_LTM <-summary_study_level_LTM %>%
  rowwise()%>%
  mutate(accuracy = (90 - accuracy_ltm))
 
ggplot(summary_stats_participant_LTM, aes(x = trial_type, y = accuracy,color = as.factor(participant))) + 
  geom_line(aes(group = participant), alpha = 1.5/5)+
  geom_point(data = summary_study_level_LTM, aes(x = trial_type, y = accuracy),  colour = "black", size =1.5 )+
  geom_errorbar(data = summary_study_level_LTM, aes(x = trial_type, ymin = accuracy-se, ymax =accuracy+se), width = .15, colour = "black", size = 0.8)+
  geom_line(data = summary_study_level_LTM, aes(x = trial_type, group = 1),  colour = "black", size =0.6 )+
  geom_text(data = summary_study_level_LTM, aes(x = trial_type, y = accuracy, label = round(accuracy, digits = 3) * (1)),
            color = "blue", vjust = -3)+
  ylim(c(-20, 90)) + 
  ylab("")+
  xlab('\n\n')+
  guides(color = "none")+
  labs(title = 'Participant means over experimental conditions in LTM')+
  theme_minimal()+
  scale_color_manual(values = green_colors) +  # Set the orangy color palette
  theme(plot.title = element_text(hjust = 0.5))+
  theme(plot.title = element_text(size = 10))



```

```{r pairwise t-test LTM, echo=FALSE}
print("The following pairwise t-test tests the difference between attended, unattended and attended/unattended never tested storage in LTM")
# 
# describeBy(full_data_summary_ltm$mean, group=full_data_summary_ltm$trial_type)
# 
full_data_summary_ltm <-data_LTM %>%
  group_by(trial_type, participant) %>%
  get_summary_stats(accuracy_ltm, type = "mean_sd")

# Create a boxplot using ggplot2
ggplot(full_data_summary_ltm, aes(x = trial_type, y = mean)) +
  geom_boxplot() +
  labs(title = "Boxplot of Mean by Trial Type",
       x = "Trial Type",
       y = "Mean") +
  theme_minimal()

# Create a boxplot using ggplot2
ggplot(full_data_summary_ltm, aes(x = trial_type, y = mean)) +
  geom_boxplot() +
  geom_text(aes(label = round(mean, digits = 2), y = mean + 5), color = "blue", size = 3) +  # Add means as numbers
  labs(title = "Boxplot of Mean by Trial Type",
       x = "Trial Type",
       y = "Mean") +
  theme_minimal()


full_data_summary_ltm <- data_LTM %>%
  group_by(trial_type, participant) %>%
  get_summary_stats(accuracy_ltm, type = "mean_sd")

# Calculate trial type group means
trial_type_means <- full_data_summary_ltm %>%
  group_by(trial_type) %>%
  summarize(group_mean = mean(mean))


# Create a color palette (you can choose any color palette you like)
my_palette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

# Create a boxplot using ggplot2
ggplot(full_data_summary_ltm, aes(x = trial_type, y = mean, fill = trial_type)) +
  geom_boxplot() +
  geom_text(data = trial_type_means, aes(label = round(group_mean, digits = 2), y = group_mean + 5),
            color = "black", size = 3, position = position_dodge(width = 0.75)) +  # Add trial type means as numbers
  labs(title = "Boxplot of Mean by Trial Type",
       x = "Trial Type",
       y = "Mean") +
  theme_minimal() +
  scale_fill_manual(values = my_palette) +  # Apply the custom color palette
  guides(fill = "none")  # Hide the legend for the fill aesthetic






full_data_summary_ltm_w<-full_data_summary_ltm[!(full_data_summary_ltm$trial_type=="unattended-never tested"),]
full_data_summary_ltw_w<-full_data_summary_ltm[!(full_data_summary_ltm$trial_type=="attended-never tested"),]

#wilcox.test(full_data_summary_ltm_w$mean ~ full_data_summary_ltm_w$trial_type, paired = TRUE, exact=FALSE, correct=TRUE, conf.int = TRUE)

full_data_summary_ltm %>%
  pairwise_t_test(
    mean ~ trial_type, paired = TRUE,
    p.adjust.method = "holm")


```




```{r accuracy LTM trial type PRUNED, echo=FALSE}

summary_stats_participant_LTM_p <- summarySE(data_LTM_pruned, measurevar = "accuracy_ltm", groupvars = c("trial_type","participant"),na.rm = T)

summary_study_level_LTM_p <- summarySE(data_LTM_pruned, measurevar = "accuracy_ltm", groupvars = c("trial_type"),na.rm = T)

# means_across_participant_LTM <- summary_stats_participant_LTM_p %>%
#   group_by(trial_type) %>%
#   summarize(mean_accuracy_ltm = mean(accuracy_ltm))
# 
# means_across_participant_LTM <- summary_stats_participant_LTM_p %>%
#   group_by(trial_type) %>%
#   summarize(mean_accuracy_ltm = mean(accuracy_ltm),
#             se= sqrt(sum(se^2) / n()))


summary_stats_participant_LTM_p <-summary_stats_participant_LTM_p %>%
  rowwise()%>%
  mutate(accuracy = (90 - accuracy_ltm))

summary_study_level_LTM_p <-summary_study_level_LTM_p %>%
  rowwise()%>%
  mutate(accuracy = (90 - accuracy_ltm))

# means_across_participant_LTM <-means_across_participant_LTM %>%
#   rowwise()%>%
#   mutate(accuracy = (90 - mean_accuracy_ltm))
 
ggplot(summary_stats_participant_LTM_p, aes(x = trial_type, y = accuracy,color = as.factor(participant))) + 
  geom_line(aes(group = participant), alpha = 1.5/5)+
  geom_point(data = summary_study_level_LTM_p, aes(x = trial_type, y = accuracy),  colour = "black", size =1.5 )+
  geom_errorbar(data = summary_study_level_LTM_p, aes(x = trial_type, ymin = accuracy-se, ymax =accuracy+se), width = .15, colour = "black", size = 0.8)+
  geom_line(data = summary_study_level_LTM_p, aes(x = trial_type, group = 1),  colour = "black", size =0.6 )+
  stat_summary(fun.y=mean, colour="blue", geom="text", show_guide = FALSE, vjust=-3, aes(label=(round(..y.., digits=1)*(1))))+
  ylim(c(-20, 90)) + 
  ylab("")+
  xlab('\n\n')+
  guides(color = "none")+
  labs(title = 'PRUNED TRIALS (mean performance): Participant means over experimental conditions in LTM')+
  theme_minimal()+
  scale_color_manual(values = green_colors) +  # Set the orangy color palette
  theme(plot.title = element_text(hjust = 0.5))+
  theme(plot.title = element_text(size = 10))


```

```{r pairwise t-test LTM pruned, echo=FALSE}
print("The following pairwise t-test tests the difference between attended, unattended and attended/unattended never tested storage in pruned LTM data")

full_data_summary_ltm_p <-data_LTM_pruned %>%
  group_by(trial_type, participant) %>%
  get_summary_stats(accuracy_ltm, type = "mean_sd")


full_data_summary_ltm_p %>%
  pairwise_t_test(
    mean ~ trial_type, paired = TRUE,
    p.adjust.method = "holm")


```






```{r accuracy LTM image effect,echo=FALSE}

summary_stats_participant_LTM_ie <- summarySE(data_LTM, measurevar = "accuracy_ltm", groupvars = c("image_effect","participant"),na.rm = T)
summary_study_level_LTM_ie <- summarySE(data_LTM, measurevar = "accuracy_ltm", groupvars = c("image_effect"),na.rm = T)

summary_stats_participant_LTM_ie <-summary_stats_participant_LTM_ie %>%
  rowwise()%>%
  mutate(accuracy = (90 - accuracy_ltm))

summary_study_level_LTM_ie <-summary_study_level_LTM_ie %>%
  rowwise()%>%
  mutate(accuracy = (90 - accuracy_ltm))


#level_order <- c('Image1-attended', 'Image2-attended', 'Image1-unattended"','Image2-unattended','Image1-attended-never tested','Image2-attended-never tested','Image1-unattended-never tested','Image2-unattended-never tested')
 
ggplot(summary_stats_participant_LTM_ie, aes(x = factor(image_effect), y = accuracy,color = as.factor(participant))) + 
  geom_line(aes(group = participant), alpha = 1.5/5)+
  geom_point(data = summary_study_level_LTM_ie, aes(x = image_effect, y = accuracy),  colour = "black", size =1.5 )+
  geom_errorbar(data = summary_study_level_LTM_ie, aes(x = image_effect, ymin = accuracy-se, ymax =accuracy+se), width = .15, colour = "black", size = 0.8)+
  geom_line(data = summary_study_level_LTM_ie, aes(x = image_effect, group = 1),  colour = "black", size =0.6 )+
  stat_summary(fun.y=mean, colour="blue", geom="text", show_guide = FALSE, vjust=-3, aes(label=(round(..y.., digits=1)*(1))))+
  ylim(c(-20, 90)) + 
  ylab("")+
  xlab('\n\n')+
  guides(color = "none")+
  labs(title = 'LTM primacy effect?')+
  theme_minimal()+
  scale_color_manual(values = green_colors) +  # Set the orangy color palette
  theme(plot.title = element_text(hjust = 0.5))+
  theme(plot.title = element_text(size = 10))+
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, vjust = 0.5))



```


## ANOVA 1
#2x2 Design of attention (attended vs. unattended) x WM vs LTM

```{r ANOVA1,echo=FALSE}

data_LTM_pruned <- data_LTM_pruned  %>% 
  mutate(attention = case_when(
    trial_type == "attended" ~ "attended",
    trial_type == "unattended" ~ "unattended",
    trial_type == "unattended-never tested" ~ "unattended",
    trial_type == "attended-never tested" ~ "attended"))

data_LTM_pruned <- data_LTM_pruned  %>% 
  mutate(testing = case_when(
    trial_type == "unattended-never tested" ~ "no",
    trial_type == "attended-never tested" ~ "no",
    trial_type == "attended" ~ "yes",
    trial_type == "unattended" ~ "yes"))


data_LTM_pruned$test <- "LTM"
data_WM$test <-"WM"

data_subset <- data_LTM_pruned %>%
  select(accuracy_ltm, trial_type,participant,test)

data_subset_WM <- data_WM%>%
  select(accuracy_t1, trial_type_new,participant,test)

colnames(data_subset)[1] = "accuracy_t1"
colnames(data_subset)[2] = "trial_type_new"

full_data <- rbind(data_subset_WM, data_subset)

full_data<-full_data[!(full_data$trial_type_new=="unattended-never tested"),]
full_data<-full_data[!(full_data$trial_type_new=="attended-never tested"),]


full_data$participant = as.factor(full_data$participant)

print("The following ANOVA displays the results of all trial conditions across the two tasks")

res.aov2 <- with(full_data,
                 aov(accuracy_t1 ~ trial_type_new * test+Error(participant)))


summary(res.aov2,detailed = TRUE)
# summary_data <- full_data %>%
#   group_by(participant, trial_type_new, test,image_presentation) %>%
#   summarize(mean_accuracy = mean(accuracy))



# res.aov2 <- with(full_data,
#                  aov(accuracy ~ trial_type_new + image_presentation* test))
```


## ANOVA 2
#2x2 Design of attention (attended vs. unattended) x tested vs untested -> To examine slopes between untested **attended** and untested **un**attended
# First for the pruned data

```{r ANOVA2 (pruned),echo=FALSE}

## next I want to look at a 2x2 ANOVA  in regard to the slope of the testing benefit in attention vs. unattention trials

res.aov4 <- with(data_LTM_pruned,
                 aov(accuracy_ltm ~ attention * testing+Error(participant)))


summary(res.aov4,detailed = TRUE)



```

# Here, for the unpruned data 

```{r ANOVA2 (unpruned),echo=FALSE}

## next I want to look at a 2x2 ANOVA  in regard to the slope of the testing benefit in attention vs. unattention trials

data_LTM <- data_LTM  %>% 
  mutate(attention = case_when(
    trial_type == "attended" ~ "attended",
    trial_type == "unattended" ~ "unattended",
    trial_type == "unattended-never tested" ~ "unattended",
    trial_type == "attended-never tested" ~ "attended"))

data_LTM <- data_LTM  %>% 
  mutate(testing = case_when(
    trial_type == "unattended-never tested" ~ "no",
    trial_type == "attended-never tested" ~ "no",
    trial_type == "attended" ~ "yes",
    trial_type == "unattended" ~ "yes"))



res.aov4 <- with(data_LTM,
                 aov(accuracy_ltm ~ attention * testing+Error(participant)))


summary(res.aov4,detailed = TRUE)



```











